# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy.

To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook.

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [2]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import numpy as np

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [3]:
# Upload credit_card_transactions.csv to Colab
from google.colab import files

csv_file = files.upload()

Saving applicants_data.csv to applicants_data.csv

In [4]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv('applicants_data.csv')

# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [5]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [6]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=['EIN','NAME'])

# Review the DataFrame
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [7]:
# Create a list of categorical variables
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [8]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [9]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [10]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names_out(categorical_variables)
)

# Review the DataFrame
encoded_df

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [11]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
numerical_applicant_data_df = applicant_data_df.drop(columns=categorical_variables)

final_encoded_df = pd.concat([
    numerical_applicant_data_df.reset_index(drop=True),
    encoded_df.reset_index(drop=True)
],axis=1)

# # Review the Dataframe
final_encoded_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [12]:
# Define the target set y using the IS_SUCCESSFUL column
y = final_encoded_df['IS_SUCCESSFUL']

# Display a sample of y
y

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [13]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = final_encoded_df.drop(columns='IS_SUCCESSFUL')

# Review the features DataFrame
X

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [14]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [15]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [16]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [17]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [18]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  (number_input_features + number_output_neurons) // 2

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [19]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1 + number_output_neurons) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [20]:
# Create the Sequential model instance
nn = Sequential()

In [21]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [22]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [23]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=number_output_neurons, activation="sigmoid"))

In [24]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 58)                6786

 dense_1 (Dense)             (None, 29)                1711

 dense_2 (Dense)             (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [25]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [26]:
# Fit the model using 50 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 3s 2ms/step - loss: 0.5771 - accuracy: 0.7186
Epoch 2/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5531 - accuracy: 0.7290
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5502 - accuracy: 0.7300
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7320
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7315
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7329
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7334
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7334
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7334
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7353
Epoch 11/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5414 - accuracy: 0.7348
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7348
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7360
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7360
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7376
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7365
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7367
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7380
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7374
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7377
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7365
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7381
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7376
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7392
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7387
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7383
Epoch 27/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7394
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7381
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7393
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7388
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7383
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7390
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7397
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7402
Epoch 35/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7403
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7397
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7399
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7394
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7405
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7405
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5335 - accuracy: 0.7402
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7406
Epoch 43/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.7402
Epoch 44/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.7406
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7407
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7411
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7409
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7404
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5322 - accuracy: 0.7402
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7405

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [27]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5615 - accuracy: 0.7308 - 724ms/epoch - 3ms/step
Loss: 0.5614610314369202, Accuracy: 0.7308454513549805

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [28]:
# Set the model's file path
file_path = 'AlphabetSoup.h5'

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [29]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [30]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [31]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = np.math.factorial(number_input_features) / np.math.factorial(number_input_features - 2)

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

13340.0

In [32]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [33]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu"))


# Output layer
nn_A1.add(Dense(units=number_output_neurons_A1, activation="sigmoid"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 13340)             1560780

 dense_4 (Dense)             (None, 1)                 13341

=================================================================
Total params: 1,574,121
Trainable params: 1,574,121
Non-trainable params: 0
_________________________________________________________________

In [34]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [35]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
804/804 [==============================] - 21s 25ms/step - loss: 0.7797 - accuracy: 0.7129
Epoch 2/50
804/804 [==============================] - 22s 28ms/step - loss: 0.8580 - accuracy: 0.7210
Epoch 3/50
804/804 [==============================] - 21s 27ms/step - loss: 0.6984 - accuracy: 0.7225
Epoch 4/50
804/804 [==============================] - 20s 25ms/step - loss: 0.6365 - accuracy: 0.7280
Epoch 5/50
804/804 [==============================] - 21s 26ms/step - loss: 0.6440 - accuracy: 0.7285
Epoch 6/50
804/804 [==============================] - 20s 25ms/step - loss: 0.7048 - accuracy: 0.7247
Epoch 7/50
804/804 [==============================] - 21s 25ms/step - loss: 0.6058 - accuracy: 0.7269
Epoch 8/50
804/804 [==============================] - 21s 26ms/step - loss: 0.5878 - accuracy: 0.7303
Epoch 9/50
804/804 [==============================] - 19s 23ms/step - loss: 0.7752 - accuracy: 0.7289
Epoch 10/50
804/804 [==============================] - 20s 25ms/step - loss: 0.6681 - accuracy: 0.7281
Epoch 11/50
804/804 [==============================] - 20s 25ms/step - loss: 0.5792 - accuracy: 0.7295
Epoch 12/50
804/804 [==============================] - 20s 25ms/step - loss: 0.5715 - accuracy: 0.7319
Epoch 13/50
804/804 [==============================] - 20s 24ms/step - loss: 0.6122 - accuracy: 0.7316
Epoch 14/50
804/804 [==============================] - 20s 25ms/step - loss: 0.6142 - accuracy: 0.7253
Epoch 15/50
804/804 [==============================] - 20s 25ms/step - loss: 0.5707 - accuracy: 0.7318
Epoch 16/50
804/804 [==============================] - 21s 26ms/step - loss: 0.5757 - accuracy: 0.7318
Epoch 17/50
804/804 [==============================] - 20s 25ms/step - loss: 0.5614 - accuracy: 0.7331
Epoch 18/50
804/804 [==============================] - 21s 26ms/step - loss: 0.8389 - accuracy: 0.7310
Epoch 19/50
804/804 [==============================] - 21s 26ms/step - loss: 0.6792 - accuracy: 0.7266
Epoch 20/50
804/804 [==============================] - 22s 27ms/step - loss: 0.5816 - accuracy: 0.7332
Epoch 21/50
804/804 [==============================] - 20s 25ms/step - loss: 0.5670 - accuracy: 0.7343
Epoch 22/50
804/804 [==============================] - 20s 25ms/step - loss: 0.5709 - accuracy: 0.7345
Epoch 23/50
804/804 [==============================] - 20s 25ms/step - loss: 0.5567 - accuracy: 0.7353
Epoch 24/50
804/804 [==============================] - 21s 26ms/step - loss: 0.5613 - accuracy: 0.7345
Epoch 25/50
804/804 [==============================] - 21s 26ms/step - loss: 0.5605 - accuracy: 0.7349
Epoch 26/50
804/804 [==============================] - 20s 24ms/step - loss: 1.0884 - accuracy: 0.7247
Epoch 27/50
804/804 [==============================] - 21s 26ms/step - loss: 0.6809 - accuracy: 0.7304
Epoch 28/50
804/804 [==============================] - 20s 25ms/step - loss: 0.6031 - accuracy: 0.7356
Epoch 29/50
804/804 [==============================] - 21s 26ms/step - loss: 0.5886 - accuracy: 0.7357
Epoch 30/50
804/804 [==============================] - 21s 26ms/step - loss: 0.7006 - accuracy: 0.7326
Epoch 31/50
804/804 [==============================] - 20s 25ms/step - loss: 0.5881 - accuracy: 0.7357
Epoch 32/50
804/804 [==============================] - 20s 24ms/step - loss: 0.5650 - accuracy: 0.7367
Epoch 33/50
804/804 [==============================] - 19s 24ms/step - loss: 0.5638 - accuracy: 0.7379
Epoch 34/50
804/804 [==============================] - 21s 26ms/step - loss: 0.5827 - accuracy: 0.7368
Epoch 35/50
804/804 [==============================] - 20s 25ms/step - loss: 0.7635 - accuracy: 0.7315
Epoch 36/50
804/804 [==============================] - 20s 25ms/step - loss: 0.5958 - accuracy: 0.7357
Epoch 37/50
804/804 [==============================] - 20s 25ms/step - loss: 0.5641 - accuracy: 0.7373
Epoch 38/50
804/804 [==============================] - 19s 24ms/step - loss: 0.5573 - accuracy: 0.7354
Epoch 39/50
804/804 [==============================] - 20s 25ms/step - loss: 0.5575 - accuracy: 0.7369
Epoch 40/50
804/804 [==============================] - 20s 25ms/step - loss: 0.5548 - accuracy: 0.7381
Epoch 41/50
804/804 [==============================] - 21s 26ms/step - loss: 0.5552 - accuracy: 0.7362
Epoch 42/50
804/804 [==============================] - 20s 25ms/step - loss: 0.5601 - accuracy: 0.7352
Epoch 43/50
804/804 [==============================] - 20s 25ms/step - loss: 1.1789 - accuracy: 0.7297
Epoch 44/50
804/804 [==============================] - 21s 26ms/step - loss: 0.9976 - accuracy: 0.7311
Epoch 45/50
804/804 [==============================] - 22s 27ms/step - loss: 0.6114 - accuracy: 0.7350
Epoch 46/50
804/804 [==============================] - 21s 26ms/step - loss: 0.5926 - accuracy: 0.7359
Epoch 47/50
804/804 [==============================] - 19s 24ms/step - loss: 0.5731 - accuracy: 0.7372
Epoch 48/50
804/804 [==============================] - 20s 25ms/step - loss: 0.5734 - accuracy: 0.7381
Epoch 49/50
804/804 [==============================] - 20s 25ms/step - loss: 0.5658 - accuracy: 0.7372
Epoch 50/50
804/804 [==============================] - 21s 26ms/step - loss: 0.5539 - accuracy: 0.7387

#### Alternative Model 2

In [36]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [37]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = number_output_neurons_A1

In [52]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = number_input_features

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

116

In [53]:
# Create the Sequential model instance
nn_A2 = Sequential()

# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation="relu"))

#Iterate the rest of the layers
number_input_features_per_layer = number_input_features // 3
number_units_per_layer = number_input_features_per_layer
while number_input_features_per_layer > 2:
  number_input_features_per_layer = number_input_features_per_layer // 2
  if number_input_features_per_layer >= 2:
    number_units_per_layer = int(np.math.factorial(number_input_features_per_layer) / np.math.factorial(number_input_features_per_layer - 2))
    nn_A2.add(Dense(units=number_units_per_layer, activation="relu"))


# Output layer
nn_A2.add(Dense(units=number_output_neurons_A1, activation="sigmoid"))


# Check the structure of the model
nn_A2.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_44 (Dense)            (None, 116)               13572

 dense_45 (Dense)            (None, 342)               40014

 dense_46 (Dense)            (None, 72)                24696

 dense_47 (Dense)            (None, 12)                876

 dense_48 (Dense)            (None, 2)                 26

 dense_49 (Dense)            (None, 1)                 3

=================================================================
Total params: 79,187
Trainable params: 79,187
Non-trainable params: 0
_________________________________________________________________

In [54]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [55]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
804/804 [==============================] - 4s 3ms/step - loss: 0.5725 - accuracy: 0.7188
Epoch 2/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5545 - accuracy: 0.7286
Epoch 3/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5509 - accuracy: 0.7318
Epoch 4/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5479 - accuracy: 0.7312
Epoch 5/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5472 - accuracy: 0.7318
Epoch 6/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5445 - accuracy: 0.7332
Epoch 7/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5445 - accuracy: 0.7350
Epoch 8/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5436 - accuracy: 0.7351
Epoch 9/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5430 - accuracy: 0.7353
Epoch 10/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5420 - accuracy: 0.7355
Epoch 11/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7372
Epoch 12/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5412 - accuracy: 0.7367
Epoch 13/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5406 - accuracy: 0.7355
Epoch 14/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5388 - accuracy: 0.7384
Epoch 15/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5387 - accuracy: 0.7374
Epoch 16/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5391 - accuracy: 0.7371
Epoch 17/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5378 - accuracy: 0.7381
Epoch 18/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5378 - accuracy: 0.7386
Epoch 19/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5371 - accuracy: 0.7378
Epoch 20/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5373 - accuracy: 0.7389
Epoch 21/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5362 - accuracy: 0.7390
Epoch 22/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7388
Epoch 23/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5358 - accuracy: 0.7387
Epoch 24/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.7392
Epoch 25/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5352 - accuracy: 0.7399
Epoch 26/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5346 - accuracy: 0.7399
Epoch 27/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5342 - accuracy: 0.7398
Epoch 28/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5348 - accuracy: 0.7393
Epoch 29/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.7407
Epoch 30/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5330 - accuracy: 0.7413
Epoch 31/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5329 - accuracy: 0.7408
Epoch 32/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5325 - accuracy: 0.7411
Epoch 33/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5328 - accuracy: 0.7399
Epoch 34/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5333 - accuracy: 0.7400
Epoch 35/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5323 - accuracy: 0.7403
Epoch 36/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5315 - accuracy: 0.7402
Epoch 37/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5323 - accuracy: 0.7406
Epoch 38/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5309 - accuracy: 0.7414
Epoch 39/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5322 - accuracy: 0.7409
Epoch 40/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5301 - accuracy: 0.7423
Epoch 41/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5317 - accuracy: 0.7421
Epoch 42/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5308 - accuracy: 0.7419
Epoch 43/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5301 - accuracy: 0.7420
Epoch 44/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5292 - accuracy: 0.7425
Epoch 45/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5293 - accuracy: 0.7427
Epoch 46/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5294 - accuracy: 0.7413
Epoch 47/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5309 - accuracy: 0.7412
Epoch 48/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5293 - accuracy: 0.7409
Epoch 49/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5295 - accuracy: 0.7417
Epoch 50/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5286 - accuracy: 0.7426

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [56]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5615 - accuracy: 0.7308 - 326ms/epoch - 1ms/step
Loss: 0.5614610314369202, Accuracy: 0.7308454513549805

In [57]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 1s - loss: 5.1647 - accuracy: 0.7297 - 1s/epoch - 5ms/step
Loss: 5.164718151092529, Accuracy: 0.72967928647995

In [58]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 1s - loss: 0.5729 - accuracy: 0.7294 - 502ms/epoch - 2ms/step
Loss: 0.5728796124458313, Accuracy: 0.7294460535049438

### Step 3: Save each of your alternative models as an HDF5 file.

In [59]:
# Set the file path for the first alternative model
file_path = 'AlphabetSoup_A1.h5'

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [60]:
# Set the file path for the second alternative model
file_path = 'AlphabetSoup_A2.h5'

# Export your model to a HDF5 file
nn_A2.save(file_path)